---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: idm-web-app
  name: idm-web-app
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: idm-web-app
  template:
    metadata:
      labels:
        app: idm-web-app
    spec:
      containers:
        - image: docker.io/t585585/idm-web-app:latest
          imagePullPolicy: IfNotPresent
          name: idm-web-app
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: idm-web-app-svc
  namespace: prod
spec:
  ports:
    - name: http-web
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: idm-web-app
  type: LoadBalancer